
ignoreFields:
  - "metadata.creationTimestamp"
  - "metadata.generation"
  - "metadata.resourceVersion"
  - "metadata.uid"
  - "metadata.selfLink"
  - "metadata.managedFields"
  - "status"
  - "spec.template.metadata.creationTimestamp"
  - "metadata.annotations.deployment.kubernetes.io/revision"
  - "status.observedGeneration"
  - "spec.clusterIP"
  - "spec.clusterIPs"
  - "spec.ipFamilies"
  - "spec.ipFamilyPolicy"
  - "metadata.annotations.kubectl.kubernetes.io/last-applied-configuration"
  - "spec.template.spec.nodeName"
  - "spec.template.spec.restartPolicy"
  - "spec.template.spec.dnsPolicy"
  - "spec.template.spec.schedulerName"
  - "spec.template.spec.securityContext"
  - "spec.template.spec.enableServiceLinks"